[project]
name = "plot"
version = "0.1.0"
description = "Plot stores and manages all scripts for the home lab."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "docs",
    "ansible",
]
