- name: upgrade | Upgrade all packages
  when:
    - ansible_facts.pkg_mgr == "apt"
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
    autoremove: true
    state: present
