- name: Install role dependencies
  ansible.builtin.include_tasks: dependencies.yml
- name: Setup proxmox to not need subscription
  ansible.builtin.include_tasks: no_subscription.yml
- name: Join cluster
  ansible.builtin.include_tasks: join_cluster.yml
