- name: Install role dependencies
  include_tasks: dependencies.yml
- name: Setup proxmox to not need subscription
  include_tasks: no_subscription.yml
- name: Join cluster
  include_tasks: join_cluster.yml
