- name: Install tailscale
  ansible.builtin.include_tasks: install.yml
- name: Join tailnet
  ansible.builtin.include_tasks: join.yml
- name: Configure certificates
  ansible.builtin.include_tasks: certs.yml
