[project]
name = "plot-ansible"
version = "0.1.0"
description = "The Ansible scripts of the Plot."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ansible>=13.3.0",
    "ansible-lint>=26.1.1",
    "ansible-vault>=4.1.0",
]
