- name: Configure proxmox cluster
  hosts: proxmox
  vars_files:
    - vars/proxmox.yml
    - vars/secrets.yml
  roles:
    - proxmox
- name: Configure all hosts
  hosts: all
  vars_files:
    - vars/secrets.yml
  roles:
    - common
    - tailscale
